version: "3.6"
services:
  web:
#    image: craftcms/nginx:8.1-dev
    build: .
    ports:
      - 8088:8080
    env_file: .env
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    networks:
      - xkp-default
    extra_hosts:
      - "host.docker.internal:10.88.0.1"
    volumes:
      - .:/app

networks:
  xkp-default:
    external: true
