version: "3.6"
services:
  web:
#    image: craftcms/nginx:8.1-dev
#    image: localhost/craftcms_web
    build: .
    ports:
      - 8088:8080
    env_file: .env
#    environment:
#      XDEBUG_CONFIG: client_host=host.podman.internal
    networks:
      - xkp-default
    extra_hosts:
      - "host.podman.internal:host-gateway"
      - "dns.podman:10.89.0.1"
    volumes:
      - .:/app:Z

networks:
  xkp-default:
    external: true
