columnSuffix: null
contentColumnType: string
fieldGroup: 4b4412cf-e0e5-4c89-a63a-0140324ae616 # Blog Post Fields
handle: postContent
instructions: null
name: 'Post Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_postcontent}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
