fieldLayouts:
  71d9eaae-73e6-42e0-be34-db7c2f5601ee:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 718144f1-042d-40fa-b4e2-e95c06f89b1e # Site Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c81fa484-6ad6-4ef5-8c4b-d097bad8cdf5
            userCondition: null
            warning: null
            width: 100
        name: Info
        uid: b03e4c0a-6b4e-4541-9b60-97185533df48
        userCondition: null
handle: siteInformation
name: 'Site Information'
sortOrder: 1
